[tool.poetry]
name = "slam-experiments"
version = "0.1.0"
description = ""
authors = ["ViV99"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
g2o-python = "^0.0.12"
jaxlie = "^1.3.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
